version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
