# Use uma imagem base para Python
FROM python:3.9

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o arquivo de requisitos e instale as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie o conteúdo do diretório src/backend para o container
COPY src/backend/ .

# Exponha a porta do FastAPI
EXPOSE 8000

# Comando para rodar o servidor FastAPI usando uvicorn
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]
